# Generated by Django 3.1.7 on 2021-03-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('category', models.CharField(max_length=200, verbose_name='类型')),
                ('username', models.CharField(blank=True, max_length=200, null=True, verbose_name='登录帐号')),
                ('password', models.CharField(blank=True, max_length=200, null=True, verbose_name='登录密码')),
                ('network', models.CharField(default='TCP', max_length=200, verbose_name='网络')),
                ('server', models.CharField(max_length=200, verbose_name='IP地址')),
                ('port', models.IntegerField(blank=True, null=True, verbose_name='端口')),
                ('database', models.CharField(max_length=200, verbose_name='数据库')),
                ('charset', models.CharField(blank=True, default='UTF-8', max_length=200, null=True, verbose_name='编码')),
                ('status', models.IntegerField(choices=[(1, '未开始'), (2, '进行中'), (3, '完成'), (3, '异常')], default=1, editable=False, verbose_name='状态')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '敏感数据发现',
                'verbose_name_plural': '敏感数据发现',
            },
        ),
    ]
