# Generated by Django 3.1.7 on 2021-03-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='charset',
            field=models.CharField(blank=True, default='UTF8', max_length=200, null=True, verbose_name='编码'),
        ),
    ]
