# Generated by Django 3.1.7 on 2021-03-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20210310_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tid',
            field=models.IntegerField(blank=True, null=True, verbose_name='下发发现id'),
        ),
    ]
