# Generated by Django 3.1.7 on 2021-03-13 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_tid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='字段名')),
                ('table_name', models.CharField(max_length=200, verbose_name='表名')),
                ('total', models.CharField(max_length=200, verbose_name='总数')),
                ('step', models.CharField(max_length=200, verbose_name='数量')),
                ('config', models.CharField(max_length=200, verbose_name='类型名称')),
                ('class1', models.CharField(max_length=200, verbose_name='一级分类')),
                ('class2', models.CharField(max_length=200, verbose_name='二级分类')),
                ('class3', models.CharField(max_length=200, verbose_name='三级分类')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Detail_task', to='task.task', verbose_name='敏感发现')),
            ],
        ),
    ]
