# Generated by Django 3.1.7 on 2021-03-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('ip', models.GenericIPAddressField()),
                ('category', models.CharField(max_length=200, verbose_name='类型')),
                ('xitong', models.CharField(max_length=200, verbose_name='系统')),
                ('bumen', models.CharField(max_length=200, verbose_name='部门')),
                ('zhongxin', models.CharField(max_length=200, verbose_name='中心')),
                ('status', models.IntegerField(choices=[(1, '正常'), (0, '时效')], default=1, verbose_name='状态')),
                ('message', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '资产管理',
                'verbose_name_plural': '资产管理',
            },
        ),
    ]
