# Generated by Django 3.1.7 on 2021-03-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='status',
            field=models.IntegerField(choices=[(1, '正常'), (0, '失效')], default=1, verbose_name='状态'),
        ),
    ]
