# Generated by Django 3.1.7 on 2021-03-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class1', models.CharField(max_length=200, verbose_name='分类1')),
                ('class2', models.CharField(max_length=200, verbose_name='分类2')),
                ('class3', models.CharField(max_length=200, verbose_name='分类3')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('dept', models.CharField(max_length=200, verbose_name='深度')),
                ('category', models.CharField(choices=[('1', '正则'), ('2', '规则'), ('3', '在之中'), ('4', '等于')], default=1, max_length=200, verbose_name='解析类型')),
                ('plan', models.TextField(verbose_name='解析方法')),
                ('desc', models.TextField(verbose_name='描述')),
                ('forward', models.CharField(max_length=20, verbose_name='涉及字段')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '分级分类',
                'verbose_name_plural': '分级分类',
            },
        ),
    ]
