# Generated by Django 3.1.7 on 2021-03-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0002_auto_20210308_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='name',
            field=models.CharField(max_length=200, verbose_name='名称'),
        ),
    ]
